const ROUTES = {
  DASHBOARD: '/dashboard',
  STUDENTS_LOGS: '/dashboard/audit-logs',
  STUDENTS_VIEW: '/dashboard/students-view',
  LOCATION_COORDINATOR_VIEW: '/dashboard/location-coordinator-view',
  LOCATION_COORDINATOR_STUDENT_TAB: '/dashboard/location-coordinator/students',
  REGISTER: '/register',
  LOGIN: '/login',
  FORGOT_PASSWORD: 'forgot-password',
  RESET_PASSWORD: '/reset-password',
  PAYPAL_CHECKOUT: '/register/paypal-checkout',
  PAYPAL_SUCCESS: '/success',
  PAYPAL_CANCEL: '/cancel',
  STUDENT_DASHBOARD: '/dashboard/students',
  REGISTRATION_DATES: '/dashboard/registration-dates',
  GRADING: '/dashboard/grading',
  // EMAIL: '/dashboard/email',
  HELP_SITE: '/dashboard/help-site',
  LOCATION_COORDINATOR_HELP_SITE: '/dashboard/location-coordinator-view/help-site',
  ADMIN_EMAIL: '/dashboard/email',
  LOCATION_COORDINATOR_EMAIL: '/dashboard/location-coordinator-view/email',
  USER_MANAGER_VIEW: '/dashboard/user-manager-view',
  ROLE_MANAGER_VIEW: '/dashboard/role-manager-view',
  REGION_MANAGER_VIEW: '/dashboard/region-manager-view',
  LOCATION_MANAGER_VIEW: '/dashboard/location-manager-view',
  COURSE_MANAGER_VIEW: '/dashboard/course-manager-view',
  EXAM_CENTER_MANAGER_VIEW: '/dashboard/exam-center-manager-view',
  ADMIN_DASHBOARD: '/dashboard/admin-dashboard',
  LC_CLASSES: '/dashboard/location-coordinator-view/classes',
  LC_STUDENTS: '/dashboard/location-coordinator-view/students',
  LC_ANNOUNCEMENTS: '/dashboard/location-coordinator-view/announcements',
  LC_SECTION_SYNC: '/dashboard/location-coordinator-view/section-sync',
  LOCATION_COORDINATOR_STUDENTS_DASHBOARD:
    '/dashboard/location-coordinator-view/student-dashboard',
  TEACHERS_RESOURCES: '/dashboard/teacher-resources',
  STUDENTS_RESOURCES: '/dashboard/student-resources',
  LOCATION_COORDINATOR_TEACHERS_RESOURCES:
    '/dashboard/location-coordinator-view/teacher-resources',
  LOCATION_COORDINATOR_STUDENTS_RESOURCES:
    '/dashboard/location-coordinator-view/student-resources',

  // teacher routes here
  TEACHER_VIEW: '/teacher-view',
  TEACHER_ATTECNDANCE_VIEW: '/teacher-view/attendance',
  MY_CLASS: '/teacher-view/my-class',
  TEACHER_SYNC_VIEW: '/teacher-view/sync-view',
  TEACHER_VIEW_EMAIL: '/teacher-view/email',

  // Academin Panel
  ACADEMIC_PANEL: '/dashboard/academic-panel',

};

const APIROUTES = {
  // registration
  GET_VALUE_BY_TYPE: '/get-value-by-type',
  POST_REGISTER: '/register',
  GET_ALL_COURSES: '/courses',
  GET_COURSES_AGE_LOCATION: '/locationCourseAgeCheck',
  GET_LOCATION_COURSE: '/locationCourse',
  GET_ACADEMIC_GRADES: '/grades',
  GET_EXTRA_CURRICULAR_ACTIVITIES: '/extracurricular',
  GET_VOLUNTEERS: '/volunteering',
  GET_DONATIONS: '/donation',
  GET_EMAIL_AVAILABILITY: '/email-availablity',
  HEAR_ABOUTS_US: '/advertise',
  GET_LOCATIONS: 'location',
  GET_LOCATIONS_BY_COURSE: '/course/locations',
  GET_LOCATIONS_BY_REGION: '/locationsWRTRegion',
  POST_FEE_STRUCTURE: '/getFeeStructure',
  POST_CREATE_COURSE: '/createCourse',
  POST_EDIT_COURSE: '/editCourse',
  // login
  GET_TOKEN_FOR_LOGIN: '/getToken',
  POST_RESET_PASSWORD: '/resetPassword',
  POST_FORGOT_PASSWORD: '/forgotPassword',
  CAPTURE_ORDER: '/payment/captureOrder',
  CAPTURE_DONATION: '/payment/donationCaptureOrder',
  CREATE_ORDER: 'payment/createOrder',
  CREATE_DONATION_ORDER: 'payment/donationOrder',
  CAPTURE_DONATION_ORDER: 'payment/donationCaptureOrder',
  GET_FEE_FOR_ENROLL: '/getFeeStructure/nextEnroll',
  // student
  GET_ALL_STUDENTS: '/students',
  GET_STUDENTS_BY_REGION: '/regionstudents',
  EDIT_STUDENT: '/student/edit',
  UPDATE_STUDENT_INFO: '/student/update-info',
  UPDATE_SIBLING_INFO: '/student/sibling/update-info',
  MOVE_STUDENT: '/move-student',
  GET_STUDENT_LOGS: '/change-logs',
  GET_STUDENT_LOG_DETAIL: '/change-logs-detail',
  GET_STUDENT_SECTIONS: '/student-section',
  GET_STUDENT_PAYMENT_INFO: '/student-payment-info',
  EDIT_PARENT: '/parent/edit',
  UPDATE_PARENT_INFO: '/parent/update-info',
  GET_STUDENT_ACCOUNT_DETAILS: '/student-account-details',
  ADD_SIBLING: '/user/sibling',
  ADD_FILTER_VIEW: '/filter-view',
  GET_FILTER_VIEWS: '/filter-view-list',
  GET_ALL_FILTERS: '/filter',
  GET_ALL_FILTERS_REGION: '/getAllFilterRegion',
  GET_NEXT_ENROLL_COURSE: '/nextEnrollCourse ',
  GET_STUDENT_MARKS: '/student-marks',
  GET_ENROLLMENT_HISTORY: '/student-enrollment-history',
  // Location coordinator
  GET_CLASSROOMS: '/classroom-list',
  ADD_TEACHER: '/bulk-create-teacher',
  GET_ACADEMIC_YEARS: '/getAcademicYears',
  GET_ASSIGNED_LOCATIONS: '/getLocationAndYearInDropdown',
  GET_ALL_TEACHERS: '/getAllTeacher             ',
  POST_ACADEMIC_INFO: '/academicInfo/createRecord',
  UPDATE_ACADEMIC_INFO: '/academicInfo/updateRecord',
  GET_STUDENTS_BY_LOCATION: '/students-by-location',
  EMAIL_TEMPLATE: '/email-template',
  GET_SECTION_DETAILS: '/getSectionDetails',
  GET_ALL_LOCATION_COURSE: '/locationCourse',
  GET_TEACHER_RESOURCE: '/getTeacherResource',
  GET_STUDENT_RESOURCE_WRTCOURCE: '/getStudentResourceWRTCourse',
  GET_LOCATION_STUDENT_DASHBOARD: '/locationStudentDashboard',
  GET_TEACHERS: '/locationDashboard/notScored/teachers',
  GET_COURSES_MANAGER: '/getAllCourses',
  GET_COURSES_MANAGER_DROPDOWN: '/getAllCourses',
  SEND_ANNOUNCEMENT: '/sendAnnouncement',
  UPDATE_STUDENT_MARKS: 'student-marks',
  UPDATE_HOMEWORK_MARKS: 'student-homework-marks',
  GET_ANNOUNCEMENT_LIST: '/getEmailAnnouncementList',
  GET_SUBSTITUTION_TAGS: '/getSubstitutionTags',
  GET_ANNOUNCEMENT_BY_ID: '/getEmailAnnouncemnet',
  GET_EMAIL_FILTERS: '/getEmailFilters',
  GET_RECIPIENTS_BY_FILTER: '/recipientsWRTFilter',
  GET_HELP_VIDEOS: '/helpVideos',
  // Academic info
  GET_ACADEMIC_INFO: '/academicInfo',
  // User Manager
  GET_ALL_USER: '/userManager/getAllUser',
  GET_ALL_USER_ROLES: '/userManager/getAllUserRoles',
  ADD_USER: '/userManager/addUser',
  EDIT_USER: '/userManager/editUser',
  GET_FILTER_LIST_USER_MANAGER: 'filters/user-manager',
  // Role Manager
  GET_ALL_ROLE: '/role',
  GET_ALL_ROLE_PERMISSIONS: '/permission',
  // Region Manager
  GET_ALL_REGION: '/regions',
  GET_COUNTRIES: '/country',
  GET_REGION_COORDINATORS: '/region-coordinator',
  GET_GEO_REGION: 'georegion',
  // Location Manager
  GET_ALL_LOCATIONS: '/location',
  ADD_UPDATE_LOCATION: '/location',
  GET_ALL_EXAM_CENTERS: '/location/examcenter',
  GET_ALL_LOCATION_COORODINATORS: 'location/coordinators',
  // Admin
  GET_UPLOADFILE: '/uploadFile',
  GET_UPLOADVIDEO: '/uploadVideo',
  ADD_HELP_VIDEO: '/helpVideos/add',
  CREATE_STUDENT_RESOURCE: '/createStudentResource',
  CANCEL_ENROLLMENT: '/academic-panel/cancel',
  DEACTIVATE_RESOURCE: '/deactivateResource',
  UPDATE_RESOURCE: '/updateStudentResource',
  IMPERSONATE_USER: '/impersonateUser',
  UPDATE_HELP_VIDEO: '/helpVideos/update',
  POST_STUDENT_MARKS_BY_QUARTER: '/student-marks-by-quarter',

  // Teacher View
  STUDENTS_BY_YEAR_AND_CLASSID: '/students-by-year-and-classId',
  ADD_REGION_DATA: '/createregion',
  EDIT_REGION_DATA: '/region',
  DEACTIVATE_HELP_VIDEO: '/helpVideos/deactivate',
  STUDENT_BY_LOCATION: '/student-by-location',
  CLASSES_TIMINGS: '/teacherPanel/quarter/classesTimings',
  CLASSES_BY_ACADEMIC_YEAR: '/classes-by-academic-year',
  GET_TEACHER_PANEL_STUDENTS: '/teacherPanel/class/students',
  MARK_STUDENT_ATTENDANCE: '/teacherPanel/markStudentAttendance',
};

export { ROUTES, APIROUTES };
